// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKDPeB-IGeTuRwPR0shIdDM6NLGf8UVkI',
    appId: '1:301517136732:web:71cb2f1e7d9da09934d799',
    messagingSenderId: '301517136732',
    projectId: 'order-analytics-d32a8',
    authDomain: 'order-analytics-d32a8.firebaseapp.com',
    storageBucket: 'order-analytics-d32a8.firebasestorage.app',
    measurementId: 'G-3BFB8VNDVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBttDULJpLn_v5HWLK9_7AZneW5LvPT6m8',
    appId: '1:301517136732:android:87c8914eba96d40c34d799',
    messagingSenderId: '301517136732',
    projectId: 'order-analytics-d32a8',
    storageBucket: 'order-analytics-d32a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwIXA-WseHKQQ7uswNKjm-7GS4z3somEw',
    appId: '1:301517136732:ios:4a205ed08db82e1134d799',
    messagingSenderId: '301517136732',
    projectId: 'order-analytics-d32a8',
    storageBucket: 'order-analytics-d32a8.firebasestorage.app',
    iosBundleId: 'com.example.orderAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwIXA-WseHKQQ7uswNKjm-7GS4z3somEw',
    appId: '1:301517136732:ios:4a205ed08db82e1134d799',
    messagingSenderId: '301517136732',
    projectId: 'order-analytics-d32a8',
    storageBucket: 'order-analytics-d32a8.firebasestorage.app',
    iosBundleId: 'com.example.orderAnalytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKDPeB-IGeTuRwPR0shIdDM6NLGf8UVkI',
    appId: '1:301517136732:web:8048b63ca11d327f34d799',
    messagingSenderId: '301517136732',
    projectId: 'order-analytics-d32a8',
    authDomain: 'order-analytics-d32a8.firebaseapp.com',
    storageBucket: 'order-analytics-d32a8.firebasestorage.app',
    measurementId: 'G-6STDCFKP9C',
  );
}
